#import <CredentialManagement/Credential.idl>
#import <DOM/AbortSignal.idl>

[Exposed=Window, SecureContext]
interface PasswordCredential : Credential {
    constructor(HTMLFormElement form);
    constructor(PasswordCredentialData data);
    readonly attribute USVString password;
};
PasswordCredential includes CredentialUserData;

dictionary PasswordCredentialData : CredentialData {
    USVString name;
    USVString iconURL;
    required USVString origin;
    required USVString password;
};

typedef (PasswordCredentialData or HTMLFormElement) PasswordCredentialInit;
